### Load in NumPy (remember to ```pip install numpy``` first)
Import the numpy library as ```np``` followed by sys module for manipulating different parts of the Python runtime environemnt. 

In [1]:
import numpy as np
import sys

### The Basics
Creating a simple a one dimensional and two dimensional arrays by passing list[s] inside the ```array()``` function.

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In order to get the dimesion of the array, use ```array_name.dim```! Do not put paranthesis after writing this, it does not accept array.ndim(). It is the attribute of a class and not a function. (Like, class variables)

In [6]:
# Getting the dimension of the array
a.ndim

1

If we want to know the nxm values of our numpy array then we find the ```.shape``` attribute for that. 

In [7]:
# Getting the number of rows and columns of the array
b.shape

(2, 3)

Find the datatype in which the numpy array is getting stored. It can go from int8, int16, int32, int64, ... and so on. 

In [9]:
# Get data-type of the array
a.dtype

dtype('int8')

In order to get the size of rows we can use ```a.itemsize``` and for getting the size of elements per row, we can use ```a.size```. You can also get the complete size by multiplying both the values.

In [16]:
# Get the size of the numpy array
a.itemsize

1

In [15]:
# Get the number of elements in a data iem
a.size

3

In [17]:
# Complete size of the array
a.itemsize * a.size

3

Alternative way to get the complete size of the array is by using the ```.nbytes``` attribute

In [18]:
# Getting complete size of the array
a.nbytes

3

Usually, floating numbers take up a lot more space than regular integers. 

In [20]:
b.itemsize

8

In [21]:
b.size

6

In [19]:
b.nbytes

48