# Accessing & Altering specific elements, rows, columns etc

In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Element Retrieval - Indexing

In [7]:
# Get a specific element from the array [row, column]
a[1][5] 

13

In [8]:
# Alternate way 01 - Providing coordinates
a[1, 5]

13

In [9]:
# Alternate way 02 - Negative Indexing
a[1, -2]

13

### Retrieving specific row and column data

In [11]:
# Get a specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Alternative - 01 (Better way of presenting code)
# We specify that we want the first row and all the column data of this row

a[0, :]

In [12]:
# Get a specific column
a[:, 2]


array([ 3, 10])

In [13]:
# Getting a little oversmart :)
# [start-index : end-index : step-size]
# Same as python lists

a[0, 1 : -1 : 2 ]
# Grabs the entire first row and gets specific elements from there based on list slicing.

array([2, 4, 6])

### Altering Elements

In [19]:
# Altering Element by targetting element coordinate
print("Old Array\n", a)
a[0,5] = 25
print("New Array\n", a)

Old Array
 [[ 1  2  3  4  5 25  7]
 [ 8  9 10 11 12 25 14]]
New Array
 [[ 1  2  3  4  5 25  7]
 [ 8  9 10 11 12 25 14]]
