# Getting to Know 3D Arrays

In [1]:
import numpy as np

Creating a 3D array by nesting of multiple lists inside the array function which accepts a list.

In [2]:
b = np.array(
    [
        [
            [1,2], 
            [3,4]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)
print(b)
print

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Accessing elements happens based on the hierarchy of lists. In the following example 

[0,0,0] -> 1

[0,0,1] -> 2

[0,1,0] -> 3

[0,1,1] -> 4

In [11]:
# Get specific Element
b[0, 1, 0]

3

In [12]:
# Replacing Elements - 1st Column
b[: , 1, : ] = [[9, 9], [8, 8]]
print(b)

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

We can carry out all sorts of replacing through list slicing and indexing as long as the size for the list being inserted remains same.