# Initializing Different Types of Arrays

In [2]:
import numpy as np

In order to create a matrix full of zeroes (with decimal point) use the ```np.zeroes``` function. 

In [13]:
# All 0s matrix
a = np.zeros((2,3)) # Specify the mxn of the matrix
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In order to create a matrix full of ones (with decimal point) use the ```np.ones``` function. 

In [5]:
# All 1s matrix
np.ones((4,2,2)) 

# You can also specify int32 in order to remove the decimal point

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
# Any other number (for example 69)
np.full((2,2), 69, dtype=float)

array([[69., 69.],
       [69., 69.]])

In the above cell, the shape of the array need not be specified as numbers but can be specified from ```array_name.shape``` as well. 

The syntax is ```np.full(reference_array.shape, number)```

The syntax is ```np.full_like(reference_array, number)```

### Generating Random Decimal Numbers
If we want a matrix of m rows and m columns then we can specify ```np.random.rand(m, n)```

In [10]:
np.random.rand(4,2)

array([[0.07153784, 0.75491759],
       [0.53912746, 0.2784532 ],
       [0.45493223, 0.41138164],
       [0.98276943, 0.25266735]])

If you are interested in creating an array which copies the shape of another array, then it can be achieved with ```np.random.random_sample(reference_array.shape)```

In [14]:
np.random.random_sample(a.shape)

array([[0.61488957, 0.40017764, 0.45570139],
       [0.46857377, 0.59077267, 0.19067539]])

Do notice how all the values lie between 0 to 1. But what is you wanted random integer values. You can unitlize the ```randint``` function

In [15]:
np.random.randint(7, size=(3, 3))
# Even though the parameter is called size here, it is shape. (Weird anomaly)

array([[5, 5, 4],
       [4, 5, 5],
       [2, 1, 1]])

You can further change the range of the numbers to be included in the randomly generated array as follows :

```randint(x, size=(m, n))``` means that your range is either (0, x) or (x, 0) depending on whether it is a negative or positive value.
 
```randitn(x, y, size=(m, n))```means that your range is (x, y) with x being the smaller value and y being the bigger value

In [20]:
np.random.randint(-4, 8, size=(3,3))

array([[ 6, -3, -4],
       [ 1, -2,  0],
       [-4,  7,  0]])

You can generate an identity matrix by specifying the number of elements per row or column you need. By default, the identity matrix is a square matrix. The function for that is -- ```identity(x)```

In [23]:
np.identity(5, dtype="int8")

# If int8 is not mentioned then this would show decimal values as well. 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

### Repeating Elements in Array
Sometimes arrays repeat certain elements which numpy can auto generate as follows :

In [29]:
arr = np.array([[1,2,3]])
print("--Axis 0--")
r1 = np.repeat(arr, 3, axis=0)
print(r1)
print("--Axis 1--")
r1 = np.repeat(arr, 3, axis=1)
print(r1)


# print("Axis 2\n")
# r1 = np.repeat(arr, 3, axis=2)


--Axis 0--
[[1 2 3]
 [1 2 3]
 [1 2 3]]
--Axis 1--
[[1 1 1 2 2 2 3 3 3]]


Note : 

```Axis = 0;``` is Repeating vertically as different rows

```Axis = 1;``` is Repeating horizontally as different columns adjacently. 

More axis can be added by not for 2 dimensional arrays, For n-dimensional arrays, n axis can be added 