## Problem-01 : Create the following array.
#### [1  1  1  1  1]

#### [1  0  0  0  1]

#### [1  0  9  0  1]

#### [1  0  0  0  1]

#### [1  1  1  1  1]

In [1]:
import numpy as np

Solution

In [5]:
# Creating a 5x5 array full of ones
output = np.ones((5,5), dtype='int')

# Creating an array full of zeroes and changing 
# the central element to 9
z = np.zeros((3,3), dtype='int')
z[1,1] = 9

# Replacing the center part of the 5x5 matrix with
# the 3x3 matrix
output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
