# Mathematics and NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a + 2 # Adds 2 to each element in the array

array([3, 4, 5, 6])

In [4]:
a - 2 # Subtracts 2 from each element in the array

array([-1,  0,  1,  2])

In [6]:
a * 2 # Multiplies each element in the array by 2

array([2, 4, 6, 8])

In [5]:
a / 2 # Divides each element in the array by 2

array([0.5, 1. , 1.5, 2. ])

All the mathematical stuff available in python can be done in numpy along with a lot more with the added benefit of speed. 

In [7]:
b = np.array([1,0,1,0])
a + b  # Adds the corresponding elements

array([2, 2, 4, 4])

In [8]:
a ** 2 # Raises each element to the mentioned power

array([ 1,  4,  9, 16])

In [10]:
np.sin(a) # Take sin(X) of all values

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra
#### Matrix Multiplication
Matric multiplication can be carried out using the ```matmul``` function

In [11]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

Finding the determinant of a matrix using the .```det()``` function inside the ```.linalg``` module of ```NumPy```

In [13]:
c = np.identity(3)
np.linalg.det(c)

# Determinant of identity matrix is 1

1.0

We can do things like 

1. Determinant
2. Trace
3. Singular Vector Decomposition
4. Eigen Values
5. Matrix Normalization
6. Inverse
7. etc...

Do refer : https://numpy.org/doc/stable/reference/routines.linalg.html



# Statistics

In [14]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

You can take, the min, max, average and other statistical data using the available functions. 

In [15]:
np.min(stats, axis=1) # Will give the min, row-wise

array([1, 4])

In [19]:
np.max(stats, axis=0) # Will give the max, column-wise

array([4, 5, 6])

Different summation tricks

In [20]:
np.sum(stats) # Sum of all the matrix in the matrix

21

In [24]:
print(np.sum(stats, axis=1)) # Takes sum row-wise
print(np.sum(stats, axis=0)) # Takes sum column-wise


[ 6 15]
[5 7 9]
