# Reorganizing Arrays
As long as the values fit in, matrices can be reshaped. 

In [1]:
import numpy as np

In [8]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

# Valid Reshaping (no mismatch between number of elements and mxn)
after = before.reshape((1,8))
print("Reshaping 01\n", after)
after = before.reshape((8,1))
print("Reshaping 02\n", after)

[[1 2 3 4]
 [5 6 7 8]]
Reshaping 01
 [[1 2 3 4 5 6 7 8]]
Reshaping 02
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Vertical Stacking Vectors

In [14]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Horizontal Stacking Vectors

In [13]:
h1 = np.ones((2,4), dtype="int")
print(h1)
h2 = np.zeros((2,2), dtype="int")
print(h2)

np.hstack((h1, h2))

[[1 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]]


array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

Observe how things are horizontally merged together in the rows. 