# Load Data From File
In an event where the data set is very small, a Pandas dataframe need not be used. NumPy can take care of such computations with matrices. 

In [2]:
import numpy as np

```genfromtxt()``` allows us to read data from txt and csv files based on a specified delimiter and the data can be manipulated in form of matrices.

In [3]:
filedata = np.genfromtxt('08-data.txt', delimiter=',', dtype='int')

# Advanced Indexing and Boolean Masking

In [4]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

We get the output as false as each value is compared with 50 and a matrix is generated which contains the result of each computation. 

In [6]:
# If you would like to get the values which follow 
# a certain constraint then the following can be used
filedata[filedata > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

You can carry out indexing with a list 

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # Returns the elements in this positons

array([2, 3, 9])

You can also give multiple conditions like

```((filedata > 50) & (filedata < 100) & (filedata != 69))```